In [4]:
import pandas as pd

arrays = [
    ["Bar","Bar","Baz","Baz","Foo","Foo","Qux","Qux"],
    ["One","Two","One","Two","One","Two","One","Two"]
]

index = pd.MultiIndex.from_arrays(arrays, names=["first", "second"])
index
df = pd.DataFrame(np.random.randn(8, 2), index=index, columns=["A", "B"])

df2 = df[:4]

df2

                     A         B
first second
Bar   One    -0.323205  2.585614
      Two    -0.640232  0.138304
Baz   One    -0.309593 -2.358395
      Two     0.767402  0.506228

In [5]:
arrays = [
   ["bar", "bar", "baz", "baz", "foo", "foo", "qux", "qux"],
   ["one", "two", "one", "two", "one", "two", "one", "two"],
]


index = pd.MultiIndex.from_arrays(arrays, names=["first", "second"])

df = pd.DataFrame(np.random.randn(8, 2), index=index, columns=["A", "B"])

df2 = df[:4]

df2

                     A         B
first second
bar   one     0.765612 -1.880941
      two    -0.384769  0.896658
baz   one    -0.676803  1.631238
      two     1.764627 -2.119268